const DB_COMP={
  // ── POWER ───────────────────────────────────────────────────────────────
  POWER_CELL:{name:'Power Cell',icon:'⚡',loc:['core'],
    tiers:[
      {name:'Basic',slots:1,pwr:0,pwr_give:10,price:500,dc:1,dur:3,rarity:'COMMON',legality:'LEGAL',autonomy:'1 scene or 1 hour if half capacity',note:'A micro universal and rechargeable power cell'},
      {name:'Standard',slots:2,pwr:0,pwr_give:20,price:1500,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',autonomy:'1 scene or 1 hour if half capacity',note:'A standard universal and rechargeable power cell'},
      {name:'Advanced',slots:3,pwr:0,pwr_give:30,price:4000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',autonomy:'1 scene or 1 hour if half capacity',note:'An advanced universal and rechargeable power cell'},
      {name:'Exotic',slots:5,pwr:0,pwr_give:40,price:12000,dc:5,dur:6,rarity:'RARE',legality:'RESTRICTED',autonomy:'1 scene or 1 hour if half capacity',note:'An exotic cutting edge universal and rechargeable power cell'},
    ]},
  SOLAR_PANEL:{name:'Solar Panel',icon:'☀',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:0,pwr_give:0,price:800,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',autonomy:'Unlimited (daylight)',note:'Unlimited autonomy in daylight. Recharges Power Cells and Energy Banks in 10 hour. No output in darkness'},
      {name:'Standard',slots:3,pwr:0,pwr_give:0,price:2500,dc:2,dur:2,rarity:'UNCOMMON',legality:'LEGAL',autonomy:'Unlimited (daylight)',note:'Unlimited autonomy in daylight. Recharges Power Cells and Energy Banks in 1 hour. No output in darkness'},
      {name:'Advanced',slots:4,pwr:0,pwr_give:0,price:8000,dc:3,dur:3,rarity:'RARE',legality:'LEGAL',autonomy:'Unlimited (daylight)',note:'Unlimited autonomy in daylight. Recharges Power Cells and Energy Banks in 5 minutes. No output in darkness'},
    ]},
  ENERGY_BANK:{name:'Energy Bank',icon:'🔋',loc:['core','int'],
    tiers:[
      {name:'Basic',slots:1,pwr:0,pwr_give:3,price:600,dc:1,dur:3,rarity:'COMMON',legality:'LEGAL',autonomy:'5 min (1scene)',note:'Extends Power Cell output — rechargeable via Solar Panel or dock station'},
      {name:'Standard',slots:2,pwr:0,pwr_give:6,price:2000,dc:2,dur:4,rarity:'UNCOMMON',legality:'LEGAL',autonomy:'1 hour',note:'Extends Power Cell output — rechargeable via Solar Panel or dock station'},
      {name:'Advanced',slots:3,pwr:0,pwr_give:12,price:7000,dc:4,dur:5,rarity:'RARE',legality:'LEGAL',autonomy:'1 day',note:'Extends Power Cell output — rechargeable via Solar Panel or dock station'},
    ]},
  FUSION_CORE:{name:'Fusion Reactor',icon:'⚛',loc:['core'],
    tiers:[
      {name:'Basic',slots:4,pwr:0,pwr_give:8,price:50000,dc:5,dur:6,rarity:'RARE',legality:'REGISTERED',autonomy:'Unlimited',note:'Low but constant output no fuel or recharge needed'},
      {name:'Standard',slots:6,pwr:0,pwr_give:16,price:100000,dc:7,dur:8,rarity:'LIMITED',legality:'RESTRICTED',autonomy:'Unlimited',note:'Low but constant output no fuel or recharge needed'},
      {name:'Advanced',slots:9,pwr:0,pwr_give:24,price:200000,dc:9,dur:10,rarity:'UNIQUE',legality:'RESTRICTED',autonomy:'Unlimited',note:'Low but constant output no fuel or recharge needed'},
    ]},
  CORONTHIA_REACTOR:{name:'Coronthia Reactor',icon:'🔥',loc:['core'],
    tiers:[
      {name:'Basic',slots:5,pwr:0,pwr_give:40,price:25000,dc:3,dur:6,rarity:'RARE',legality:'REGISTERED',autonomy:'1 scene per fuel unit',note:'High-output Coronthia reactor requires Fuel Cell'},
      {name:'Standard',slots:8,pwr:0,pwr_give:65,price:50000,dc:5,dur:8,rarity:'LIMITED',legality:'REGISTERED',autonomy:'1 scene per fuel unit',note:'High-output Coronthia reactor requires Fuel Cell'},
      {name:'Advanced',slots:12,pwr:0,pwr_give:100,price:100000,dc:7,dur:10,rarity:'UNIQUE',legality:'RESTRICTED',autonomy:'1 scene per fuel unit',note:'High-output Coronthia reactor requires Fuel Cell'},
    ]},
  FUEL_CELL:{name:'Fuel Cell',icon:'🛢',loc:['core','int'],
    tiers:[
      {name:'Basic',slots:1,pwr:0,price:1000,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',autonomy:'1 fuel unit',note:'Required for Coronthia Reactor provides 1 unit of fuel capacity'},
      {name:'Standard',slots:2,pwr:0,price:3000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',autonomy:'5 fuel units',note:'Required for Coronthia Reactor provides 5 units of fuel capacity'},
      {name:'Advanced',slots:3,pwr:0,price:9000,dc:4,dur:6,rarity:'RARE',legality:'LEGAL',autonomy:'10 fuel units',note:'Required for Coronthia Reactor provides 10 units of fuel capacity'},
    ]},
  // ── PROPULSION (secondary drives) ───────────────────────────────────────
  DRIVE_AQUATIC:{name:'Aquatic Drive',icon:'🌊',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:2000,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Waterproof propulsion system, swim speed 8. Operates in water environments.',mode:'Swim',speed:8},
      {name:'Standard',slots:3,pwr:4,price:6000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:'High-performance aquatic drive, swim speed 14. Suitable for rivers and open water.',mode:'Swim',speed:14},
      {name:'Advanced',slots:4,pwr:5,price:18000,dc:5,dur:6,rarity:'RARE',legality:'RESTRICTED',note:'Military-grade aquatic propulsion, swim speed 18. Depth rated to 2km.',mode:'Swim',speed:18},
    ]},
  DRIVE_CLIMBER:{name:'Climbing Drive',icon:'🦎',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:2500,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Adhesion drive for vertical and inverted movement, climb speed 8. Works on most surfaces.',mode:'Climb',speed:8},
      {name:'Standard',slots:3,pwr:3,price:6000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:'Enhanced climbing drive, climb speed 12. Metal surfaces only.',mode:'Climb',speed:12},
      {name:'Advanced',slots:4,pwr:4,price:15000,dc:5,dur:5,rarity:'RARE',legality:'LEGAL',note:'Advanced all-surface adhesion system, climb speed 16. Works on any surface including glass and stone.',mode:'Climb',speed:16},
    ]},
  DRIVE_TRACKED:{name:'Tracked Drive',icon:'🚜',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:1500,dc:2,dur:5,rarity:'COMMON',legality:'LEGAL',note:'Rugged ground drive with caterpillar tracks, track speed 8. Reliable on rough terrain.',mode:'Track',speed:8},
      {name:'Standard',slots:3,pwr:3,price:4000,dc:3,dur:7,rarity:'UNCOMMON',legality:'LEGAL',note:'Heavy-duty tracked propulsion, track speed 12. Handles mud, rubble and broken ground.',mode:'Track',speed:10},
      {name:'Advanced',slots:4,pwr:4,price:10000,dc:4,dur:10,rarity:'RARE',legality:'RESTRICTED',note:'Reinforced tracked drive, track speed 10. Gains +3 Durability bonus from hardened treads and stabilizers.',dur_bonus:3,mode:'Track',speed:12},
    ]},
  DRIVE_HOVER:{name:'Hover Drive',icon:'💨',loc:['ext'],
    tiers:[
      {name:'Basic',slots:3,pwr:4,price:4000,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Antigravity hover drive, hovers at speed 12. Operates a few meters above the ground.',mode:'Hover',speed:12},
      {name:'Standard',slots:4,pwr:6,price:10000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:'High-performance hover drive, speed 18. Smooth movement over any terrain.',mode:'Hover',speed:18},
      {name:'Advanced',slots:5,pwr:8,price:30000,dc:5,dur:6,rarity:'RARE',legality:'RESTRICTED',note:'Military-grade hover drive, speed 24. Restricted due to propulsion signature.',mode:'Hover',speed:24},
    ]},
  DRIVE_FLYER:{name:'Flight Drive',icon:'🦅',loc:['ext'],
    tiers:[
      {name:'Basic',slots:4,pwr:5,price:8000,dc:3,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Atmospheric flight drive, fly speed 20. Requires open airspace.',mode:'Fly',speed:20},
      {name:'Standard',slots:5,pwr:8,price:18000,dc:4,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:'High-performance flight drive, fly speed 30. Extended range and altitude capability.',mode:'Fly',speed:30},
      {name:'Advanced',slots:6,pwr:12,price:50000,dc:6,dur:6,rarity:'RARE',legality:'RESTRICTED',note:'Elite military-grade flight system, fly speed 40. Restricted for high-performance aerospace operations.',mode:'Fly',speed:40},
    ]},
  JUMP_JETS:{name:'Jump Jets',icon:'🚀',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:3,price:3000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Burst-leap propulsion for obstacle clearance, leap distance 8. 3 bursts before recharge.',mode:'Leap',speed:8},
      {name:'Standard',slots:3,pwr:5,price:8000,dc:4,dur:4,rarity:'RARE',legality:'RESTRICTED',note:'Enhanced jump jets, leap distance 15. 5 bursts before recharge.',mode:'Leap',speed:15},
      {name:'Advanced',slots:4,pwr:8,price:20000,dc:6,dur:5,rarity:'LIMITED',legality:'CLASSIFIED',note:'Advanced military jump system, leap distance 25. Unlimited short burst jumps. Classified system.',mode:'Leap',speed:25},
    ]},
  DRIVE_OVERHAUL:{name:'Drive Overhaul',icon:'⚙',loc:['core','int'],
    tiers:[
      {name:'Basic',slots:1,pwr:0,price:1000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Optimizes the primary drive for a modest performance boost, increasing speed by +1 with no durability impact.',spd_mod:1},
      {name:'Standard',slots:2,pwr:1,price:4500,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Enhanced drive components deliver +2 speed, but the added strain reduces durability by 2.',spd_mod:2,dur_bonus:-2},
      {name:'Advanced',slots:2,pwr:2,price:13000,dc:5,dur:3,rarity:'RARE',legality:'RESTRICTED',note:'Aggressive tuning pushes the drive to +3 speed, at the cost of 4 durability.',spd_mod:3,dur_bonus:-4},
      {name:'Exotic',slots:5,pwr:4,price:38000,dc:7,dur:2,rarity:'LIMITED',legality:'CLASSIFIED',note:'Maximizes drive output for a massive +5 speed increase. This extreme configuration is highly fragile, reducing durability by 8.',spd_mod:5,dur_bonus:-8},
    ]},
  WEIGHT_REDUCTION:{name:'Weight Reduction',icon:'⬇',loc:['ext','int'],
    tiers:[
      {name:'Basic',slots:1,pwr:0,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Lightweight alloy replaces heavy elements. +1 speed, -3 durability.',spd_mod:1,dur_bonus:-3},
      {name:'Standard',slots:1,pwr:0,price:7000,dc:4,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Ultra-light carbon composite chassis. +2 speed, -5 durability.',spd_mod:2,dur_bonus:-5},
      {name:'Advanced',slots:2,pwr:0,price:18000,dc:5,dur:4,rarity:'RARE',legality:'LEGAL',note:'Aerodynamic shell — cuts drag and mass. +3 speed, -7 durability.',spd_mod:3,dur_bonus:-7},
    ]},
  CARGO_HARDPOINT:{name:'Cargo Hardpoint',icon:'🪝',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:0,price:500,dc:1,dur:5,rarity:'COMMON',legality:'LEGAL',note:'External cargo hardpoint, -2 speed penalty. 6 SU (6 small / 2 large items).',spd_mod:-2,dur_bonus:0},
      {name:'Standard',slots:3,pwr:0,price:1500,dc:2,dur:6,rarity:'COMMON',legality:'LEGAL',note:'Large cargo hardpoint, -4 speed penalty. 20 SU (20 small / 6 large items).',spd_mod:-4,dur_bonus:0},
      {name:'Advanced',slots:5,pwr:0,price:5000,dc:3,dur:8,rarity:'UNCOMMON',legality:'LEGAL',note:'Heavy-duty reinforced cargo frame, -6 speed / +2 system. 60 SU (20 large / 60 small items), reinforced frame.',spd_mod:-6,dur_bonus:2},
    ]},
  // ── SENSING ─────────────────────────────────────────────────────────────
  SENSOR_OPTICAL:{name:'Optical Sensor',icon:'👁',loc:['core','int','ext'],
    tiers:[
      {name:'Basic',slots:1,pwr:1,price:500,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Basic optical camera array, awareness +1, sensor range 20m. Provides visual detection and identification.',awareness:1,range:'20m'},
      {name:'Standard',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'High-definition optical sensor suite, awareness +2, sensor range 60m. Enhanced zoom and low-light capability.',awareness:2,range:'60m'},
      {name:'Advanced',slots:3,pwr:3,price:8000,dc:4,dur:4,rarity:'RARE',legality:'LEGAL',note:'Advanced multi-spectrum optics, awareness +3, sensor range 200m. Includes thermal overlay and image enhancement.',awareness:3,range:'200m'},
      {name:'Exotic',slots:4,pwr:5,price:25000,dc:6,dur:5,rarity:'LIMITED',legality:'RESTRICTED',note:'Cutting-edge exotic optical array, awareness +4, sensor range 500m. Full-spectrum analysis and target classification.',awareness:4,range:'500m'},
    ]},
  SENSOR_THERMAL:{name:'Thermal Sensor',icon:'🌡',loc:['core','int','ext'],
    tiers:[
      {name:'Basic',slots:1,pwr:2,price:800,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Basic heat-signature detector, awareness +1, sensor range 15m. Detects living beings and hot machinery.',awareness:1,range:'15m'},
      {name:'Standard',slots:2,pwr:3,price:3000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard thermal imaging suite, awareness +2, sensor range 50m. Identifies heat signatures through light cover.',awareness:2,range:'50m'},
      {name:'Advanced',slots:3,pwr:4,price:10000,dc:4,dur:4,rarity:'RARE',legality:'LEGAL',note:'Advanced thermal sensor, awareness +3, sensor range 150m. Detects residual heat traces and cloaked targets.',awareness:3,range:'150m'},
    ]},
  SENSOR_CHEMICAL:{name:'Chemical Sensor',icon:'🧪',loc:['int','ext'],
    tiers:[
      {name:'Basic',slots:1,pwr:1,price:600,dc:2,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Basic chemical detection array, awareness +1, sensor range 10m. Detects explosives, drugs, biologicals.',awareness:1,range:'10m'},
      {name:'Standard',slots:2,pwr:2,price:3000,dc:3,dur:3,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Standard chemical analysis sensor, awareness +2, sensor range 30m. Full chemical analysis of detected substances.',awareness:2,range:'30m'},
      {name:'Advanced',slots:2,pwr:3,price:10000,dc:5,dur:3,rarity:'RARE',legality:'ILLEGAL',note:'Advanced restricted chemical sensor, awareness +3, sensor range 100m. Detects nerve agents and bioweapons. Illegal to operate without authorization.',awareness:3,range:'100m'},
    ]},
  SENSOR_BIOMETRIC:{name:'Biometric Sensor',icon:'🧬',loc:['int','ext'],
    tiers:[
      {name:'Basic',slots:1,pwr:1,price:1000,dc:2,dur:2,rarity:'UNCOMMON',legality:'LEGAL',note:'Basic biometric scanner, awareness +1, sensor range 10m. Reads biometrics and ID implants.',awareness:1,range:'10m'},
      {name:'Standard',slots:2,pwr:3,price:5000,dc:3,dur:3,rarity:'RARE',legality:'RESTRICTED',note:'Standard life-signs sensor, awareness +2, sensor range 10m. Full life-signs analysis including medical status.',awareness:2,range:'20m'},
      {name:'Advanced',slots:3,pwr:4,price:20000,dc:6,dur:3,rarity:'LIMITED',legality:'CLASSIFIED',note:'Classified biometric suite, awareness +3, sensor range 10m. Behavioral and emotional analysis.',awareness:3,range:'10m'},
    ]},
  SENSOR_EM:{name:'EM Sensor',icon:'📡',loc:['core','int','ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:1200,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Basic electromagnetic detector, awareness +1, sensor range 10m or DATACOM. Detects powered devices and active electronics.',awareness:1,range:'30m'},
      {name:'Standard',slots:3,pwr:3,price:4000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard EM intercept suite, awareness +2, sensor range 10m or DATACOM. Full spectrum radio intercept capability.',awareness:2,range:'100m'},
      {name:'Advanced',slots:4,pwr:5,price:15000,dc:5,dur:4,rarity:'RARE',legality:'RESTRICTED',note:'Advanced military EM sensor, awareness +3, sensor range 10m or DATACOM. Comms intercept and decryption. Restricted use.',awareness:3,range:'1km'},
    ]},
  SENSOR_TRACKING:{name:'Tracking System',icon:'🎯',loc:['core','int','ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:1500,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Basic tracking system, awareness +1, sensor range 50m. Locks on and follows a single designated target.',awareness:1,range:'50m'},
      {name:'Standard',slots:3,pwr:4,price:6000,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard multi-target tracker, awareness +2, sensor range 150m. Tracks up to 20 targets simultaneously.',awareness:2,range:'150m'},
      {name:'Advanced',slots:4,pwr:6,price:20000,dc:6,dur:5,rarity:'RARE',legality:'CLASSIFIED',note:'Advanced networked tracking system, awareness +3, sensor range 500m. Network target sharing with allied units.',awareness:3,range:'500m'},
    ]},
  // ── DEFENSE ─────────────────────────────────────────────────────────────
  ARMOR_COMBAT:{name:'Combat Armor',icon:'🛡',loc:['ext'],exclusive:true,
    tiers:[
      {name:'Basic',slots:2,pwr:0,price:2000,dc:2,dur:6,rarity:'COMMON',legality:'LEGAL',note:'Basic drone combat plating. Soak 1D+2, low protection across all types, -1 speed. Better than nothing but not by much.',spd_mod:-1,soak_bonus:'1D+2',phys:'LOW',energy:'LOW',tech:'LOW',spirit:'LOW'},
      {name:'Standard',slots:4,pwr:0,price:5000,dc:3,dur:8,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard combat armor, soak 3D+2. High physical / low energy defense, -2 speed.',spd_mod:-2,soak_bonus:'3D+2',phys:'MEDIUM',energy:'LOW',tech:'LOW',spirit:'LOW'},
      {name:'Advanced',slots:8,pwr:0,price:15000,dc:5,dur:10,rarity:'RARE',legality:'RESTRICTED',note:'Advanced reinforced combat plating, soak 5D+3. High physical, medium energy and tech defense, -4 speed.',spd_mod:-4,soak_bonus:'5D+3',phys:'HIGH',energy:'MEDIUM',tech:'MEDIUM',spirit:'LOW'},
      {name:'Exotic',slots:12,pwr:0,price:45000,dc:7,dur:14,rarity:'LIMITED',legality:'CLASSIFIED',note:'Exotic classified battle armor, soak 6D+4. High physical and energy / medium tech and spirit defense, -7 speed.',spd_mod:-7,soak_bonus:'6D+4',phys:'HIGH',energy:'HIGH',tech:'MEDIUM',spirit:'MEDIUM'},
    ]},
  ARMOR_TECH:{name:'Tech-Resist Armor',icon:'🔮',loc:['ext'],exclusive:true,
    tiers:[
      {name:'Basic',slots:2,pwr:1,price:3000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:'Basic tech-resist plating, soak 0D+3. Low protection across all types. Hardened against electronic warfare.',spd_mod:0,soak_bonus:'0D+3',phys:'LOW',energy:'LOW',tech:'LOW',spirit:'LOW'},
      {name:'Standard',slots:4,pwr:2,price:8000,dc:4,dur:7,rarity:'RARE',legality:'RESTRICTED',note:'Standard tech-resistant armor, soak 1D+4. Medium tech defense. -2 speed penalty.',spd_mod:-2,soak_bonus:'1D+4',phys:'LOW',energy:'LOW',tech:'MEDIUM',spirit:'LOW'},
      {name:'Advanced',slots:8,pwr:3,price:25000,dc:6,dur:10,rarity:'LIMITED',legality:'CLASSIFIED',note:'Advanced tech-resist shell, soak 3D+3. High tech / medium physical and energy defense, -4 speed.',spd_mod:-4,soak_bonus:'3D+3',phys:'MEDIUM',energy:'MEDIUM',tech:'HIGH',spirit:'LOW'},
    ]},
  ARMOR_SPIRIT:{name:'Spiritual Shielding',icon:'✨',loc:['ext'],exclusive:true,
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:5000,dc:4,dur:4,rarity:'RARE',legality:'LEGAL',note:'Basic spiritual shielding, soak 1D. Low protection against all types. Rare and legally available.',spd_mod:0,soak_bonus:'1D',phys:'LOW',energy:'LOW',tech:'LOW',spirit:'LOW'},
      {name:'Standard',slots:4,pwr:3,price:15000,dc:6,dur:6,rarity:'LIMITED',legality:'RESTRICTED',note:'Standard spirit-resist plating, soak 1D+2. Medium spirit defense, -2 speed.',spd_mod:-2,soak_bonus:'1D+2',phys:'LOW',energy:'LOW',tech:'LOW',spirit:'MEDIUM'},
      {name:'Advanced',slots:9,pwr:5,price:50000,dc:8,dur:8,rarity:'UNIQUE',legality:'CLASSIFIED',note:'Advanced spiritual armor, soak 2D+2. High spirit / medium physical, energy and tech defense, -4 speed. Unique and classified.',spd_mod:-4,soak_bonus:'2D+2',phys:'MEDIUM',energy:'MEDIUM',tech:'MEDIUM',spirit:'HIGH'},
    ]},
  SHIELD_ENERGY:{name:'Forcefield',icon:'💠',loc:['ext'],exclusive:true,
    tiers:[
      {name:'Basic',slots:3,pwr:4,price:5000,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Energy shield projector. Absorbs 1 hit 6 dmg, recharge 1 round. Low defenses.',soak_bonus:'0D+6',phys:'LOW',energy:'LOW',tech:'LOW',spirit:'LOW'},
      {name:'Standard',slots:4,pwr:7,price:15000,dc:5,dur:5,rarity:'RARE',legality:'RESTRICTED',note:'Standard forcefield emitter. Absorbs 1 hit 8 dmg, recharge 1 round. Medium defenses.',soak_bonus:'0D+8',phys:'MEDIUM',energy:'MEDIUM',tech:'MEDIUM',spirit:'MEDIUM'},
      {name:'Advanced',slots:9,pwr:12,price:45000,dc:7,dur:6,rarity:'LIMITED',legality:'CLASSIFIED',note:'Heavy-duty forcefield system. Absorbs 1 hit 10 dmg, recharge 1 round. High defenses.',soak_bonus:'0D+10',phys:'HIGH',energy:'HIGH',tech:'HIGH',spirit:'HIGH'},
    ]},
  REACTIVE_ARMOR:{name:'Energy Armor',icon:'💥',loc:['ext'],
    tiers:[
      {name:'ERA Panels',slots:2,pwr:0,price:3000,dc:3,dur:4,rarity:'UNCOMMON',legality:'RESTRICTED',note:'ERA panel array, soak 1D physical. Single-use blast absorption per panel. -1 speed.',spd_mod:-1,soak_bonus:'1D',phys:'LOW',energy:'NONE',tech:'NONE',spirit:'NONE'},
      {name:'NERA Array',slots:6,pwr:1,price:10000,dc:4,dur:5,rarity:'RARE',legality:'CLASSIFIED',note:'NERA active counter-blast system, soak 1D+2 physical / medium physical. Triggers counter-explosions against incoming rounds. -2 speed.',spd_mod:-2,soak_bonus:'1D+2',phys:'MEDIUM',energy:'LOW',tech:'NONE',spirit:'NONE'},
      {name:'Trophy System',slots:8,pwr:3,price:30000,dc:6,dur:6,rarity:'LIMITED',legality:'CLASSIFIED',note:'Trophy active protection system, soak 2D+2 physical / high physical and medium energy. Intercepts incoming projectiles before impact. -3 speed. Classified.',spd_mod:-3,soak_bonus:'2D+2',phys:'HIGH',energy:'MEDIUM',tech:'NONE',spirit:'NONE'},
    ]},
  HULL_REINFORCE:{name:'Hull Reinforcement',icon:'🔩',loc:['ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:0,price:1500,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Sacrificial outer plates. +3 durability. -1 speed.',spd_mod:-1,dur_bonus:3},
      {name:'Standard',slots:3,pwr:0,price:5000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard composite hull reinforcement, +6 durability. Layered composite hull reinforcement. -2 speed.',spd_mod:-2,dur_bonus:6},
      {name:'Advanced',slots:7,pwr:0,price:14000,dc:5,dur:5,rarity:'RARE',legality:'LEGAL',note:'Advanced molecular-weave hull, +9 durability. Ultra-dense shell resists structural damage. -3 speed.',spd_mod:-3,dur_bonus:9},
      {name:'Exotic',slots:10,pwr:2,price:40000,dc:7,dur:6,rarity:'LIMITED',legality:'CLASSIFIED',note:'Exotic self-sealing nanomaterial hull, +12 durability. -2 speed. Classified.',spd_mod:-2,dur_bonus:12},
    ]},
  REPAIR_SYS:{name:'Auto-Repair System',icon:'🩺',loc:['core','int'],
    tiers:[
      {name:'Basic',slots:1,pwr:1,price:1200,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Basic self-repair nanites. Restores 1 Durability per round, fully repairs post-combat.',sys_bonus:0},
      {name:'Standard',slots:2,pwr:2,price:4500,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard repair system, +1 sys bonus. Restores 2 Durability per round, fully repairs post-combat.',sys_bonus:1},
      {name:'Advanced',slots:3,pwr:4,price:15000,dc:6,dur:5,rarity:'RARE',legality:'LEGAL',note:'Advanced repair system, +2 sys bonus. Restores 3 Durability per round, fully repairs post-combat.',sys_bonus:2},
    ]},
  // ── WEAPONS ─────────────────────────────────────────────────────────────
  WEAPON_MOUNT:{name:'Weapon Mount',icon:'🔫',loc:['ext','int'],
    tiers:[
      {name:'Lt. Energy Mount',slots:2,pwr:3,price:1500,dc:2,dur:5,rarity:'COMMON',legality:'LEGAL',note:'Light energy weapon hardpoint. Fits small energy weapons. No ammo storage required.',weapon_type:'ENERGY',weapon_size:'Small',needs_ammo:false},
      {name:'Lt. Kinetic Mount',slots:2,pwr:1,price:1200,dc:2,dur:6,rarity:'COMMON',legality:'LEGAL',note:'Light ammo weapon hardpoint. Fits small ammo based  weapons. Requires ammo.',weapon_type:'KINETIC',weapon_size:'Small',needs_ammo:true},
      {name:'Md. Energy Mount',slots:3,pwr:5,price:4000,dc:3,dur:5,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Medium energy weapon hardpoint. Fits medium energy weapons. Restricted installation.',weapon_type:'ENERGY',weapon_size:'Medium',needs_ammo:false},
      {name:'Md. Kinetic Mount',slots:3,pwr:2,price:3500,dc:3,dur:7,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Medium ammo weapon hardpoint. Fits medium ammo based weapons. Requires ammo. Restricted.',weapon_type:'KINETIC',weapon_size:'Medium',needs_ammo:true},
      {name:'Hvy. Energy Mount',slots:8,pwr:9,price:12000,dc:5,dur:6,rarity:'RARE',legality:'CLASSIFIED',note:'Heavy energy weapon platform. Fits large energy weapons. Classified military hardware.',weapon_type:'ENERGY',weapon_size:'Large',needs_ammo:false},
      {name:'Hvy. Kinetic Mount',slots:8,pwr:3,price:10000,dc:5,dur:8,rarity:'RARE',legality:'CLASSIFIED',note:'Heavy ammo weapon platform. Fits large ammo based weapons. Requires ammo. Classified.',weapon_type:'KINETIC',weapon_size:'Large',needs_ammo:true},
      {name:'Auto-Turret',slots:8,pwr:4,price:20000,dc:6,dur:7,rarity:'LIMITED',legality:'CLASSIFIED',note:'Auto-targeting dual kinetic turret. Fits medium kinetic weapons with integrated auto-aim. Dual-barrel auto-targeting. Classified.',weapon_type:'KINETIC',weapon_size:'Medium',needs_ammo:true,auto_aim:true},
    ]},
  AMMO_STORAGE:{name:'Ammo Storage',icon:'📦',loc:['int','ext'],
    tiers:[
      {name:'Basic Mag',slots:1,pwr:0,price:300,dc:1,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Basic magazine attachment. Holds 2 units of ammo for kinetic weapons.',ammo_cap:2},
      {name:'Ammo Locker',slots:2,pwr:0,price:800,dc:2,dur:5,rarity:'COMMON',legality:'LEGAL',note:'Standard ammo locker. Holds 5 units of ammo.',ammo_cap:5},
      {name:'Hardened Mag',slots:2,pwr:0,price:2000,dc:2,dur:8,rarity:'UNCOMMON',legality:'LEGAL',note:'Blast-resistant hardened magazine. Holds 5 units of ammo. Explosion-proof casing.',ammo_cap:5},
      {name:'Expanded Bay',slots:3,pwr:0,price:2500,dc:3,dur:5,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Expanded ammo bay. Holds 10 units of ammo. Requires restricted permit.',ammo_cap:10},
      {name:'Reloader Sys.',slots:3,pwr:2,price:8000,dc:4,dur:6,rarity:'RARE',legality:'CLASSIFIED',note:'Auto-reloading ammo system. Holds 10 units. Auto-reloads between rounds. Classified.',ammo_cap:10},
    ]},
  // ── COMBAT SUPPORT ──────────────────────────────────────────────────────
  TARGETING_COMP:{name:'Targeting Computer',icon:'🎯',loc:['core','int'],
    tiers:[
      {name:'Basic',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Basic targeting computer. Eliminate medium range penalty to attacks.'},
      {name:'Standard',slots:3,pwr:3,price:6000,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Standard targeting system. Eliminate medium and long range penalty to attacks.'},
      {name:'Advanced',slots:4,pwr:5,price:18000,dc:5,dur:5,rarity:'RARE',legality:'RESTRICTED',note:'Advanced target-lock system. Eliminate medium to long range and movement penalty to attacks.'},
      {name:'Exotic',slots:8,pwr:7,price:50000,dc:7,dur:6,rarity:'LIMITED',legality:'CLASSIFIED',note:'Exotic combat AI. Eliminate any and all penalty to attacks.'},
    ]},
  ECM_SUITE:{name:'ECM Suite',icon:'📻',loc:['int','ext'],
    tiers:[
      {name:'Basic',slots:2,pwr:3,price:3000,dc:3,dur:3,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Basic ECM suite, ECM rating 1. Disrupts enemy comms and sensors in vicinity.',ecm:1},
      {name:'Standard',slots:3,pwr:5,price:9000,dc:5,dur:4,rarity:'RARE',legality:'CLASSIFIED',note:'Standard electronic warfare suite, ECM rating 2. Jams radar, comms and guidance systems.',ecm:2},
      {name:'Advanced',slots:7,pwr:8,price:28000,dc:7,dur:5,rarity:'LIMITED',legality:'CLASSIFIED',note:'Advanced EM warfare platform, ECM rating 3. Active and passive EM warfare suite. Classified.',ecm:3},
    ]},
  STEALTH_SYSTEM:{name:'Stealth System',icon:'👻',loc:['int','ext'],
    tiers:[
      {name:'Stealth Coat',slots:2,pwr:1,price:15000,dc:4,dur:2,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Stealth coating, radar absorbing. SMALL penalty to type I and II detection. Restricted.'},
      {name:'Adaptive Camo',slots:3,pwr:3,price:150000,dc:5,dur:3,rarity:'RARE',legality:'CLASSIFIED',note:'Adaptive camouflage system. LARGE penalty to type I and II detection. Classified.'},
      {name:'Full Stealth',slots:8,pwr:5,price:300000,dc:7,dur:4,rarity:'LIMITED',legality:'CLASSIFIED',note:'Full stealth suite. LARGE penalty to type I, II and III detection. Classified.'},
    ]},
  // ── MANIPULATION ────────────────────────────────────────────────────────
  ARM_GRIPPER:{name:'Gripper Arm',icon:'🦾',loc:['ext'],
    tiers:[
      {name:'Basic Gripper',slots:2,pwr:2,price:2000,dc:2,dur:5,rarity:'COMMON',legality:'LEGAL',note:' Single gripper arm. MIGHT 4. No fine motor. Can perform MIGHT checks up to MIGHT 4.',arms:1,str:5,fine_motor:false},
      {name:'Dual Grippers',slots:3,pwr:3,price:5000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:' Dual gripper arms. MIGHT 6. No fine motor. Can perform MIGHT checks up to MIGHT 6.',arms:2,str:6,fine_motor:false},
      {name:'Heavy Clamp',slots:3,pwr:4,price:10000,dc:4,dur:7,rarity:'UNCOMMON',legality:'LEGAL',note:' Single industrial clamp. MIGHT 8. No fine motor. Can perform MIGHT checks up to MIGHT 8.',arms:1,str:14,fine_motor:false},
      {name:'Industrial Arm',slots:9,pwr:6,price:30000,dc:5,dur:8,rarity:'RARE',legality:'RESTRICTED',note:' Dual industrial arms. MIGHT 10. No fine motor. Can perform MIGHT checks up to MIGHT 10. Restricted.',arms:2,str:18,fine_motor:false},
    ]},
  ARM_PRECISION:{name:'Precision Arm',icon:'✋',loc:['ext'],
    tiers:[
      {name:'Surgeon Limb',slots:2,pwr:3,price:4000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Can perform any physical skill check at a SMALL penalty. Limited to Tiny and Small items if using items.',arms:1,str:4,fine_motor:true},
      {name:'Micro-Tools',slots:3,pwr:4,price:10000,dc:4,dur:4,rarity:'RARE',legality:'LEGAL',note:'Can perform any physical skill check. Limited to Medium and smaller if using items.',arms:2,str:4,fine_motor:true},
      {name:'Nanotech Hand',slots:4,pwr:5,price:30000,dc:6,dur:3,rarity:'LIMITED',legality:'RESTRICTED',note:'Can perform any physical skill check at a SMALL bonus. Limited to Large and smaller if using items.',arms:1,str:3,fine_motor:true},
    ]},
  ARM_HEAVY:{name:'Heavy Arm',icon:'💪',loc:['ext'],
    tiers:[
      {name:'Exo Strut',slots:10,pwr:4,price:6000,dc:3,dur:6,rarity:'UNCOMMON',legality:'LEGAL',note:' Single heavy arm. Carry 200kg / Lift 1000kg / Push 2000kg. No fine motor. Restricted.',arms:1,str:12,fine_motor:false},
      {name:'Combat Arm',slots:20,pwr:6,price:15000,dc:5,dur:8,rarity:'RARE',legality:'RESTRICTED',note:' Dual heavy arms. Carry 500kg / Lift 2500kg / Push 5000kg. No fine motor. +2 durability. Restricted.',dur_bonus:2,arms:2,str:16,fine_motor:false},
      {name:'Siege Limbs',slots:30,pwr:9,price:45000,dc:7,dur:10,rarity:'LIMITED',legality:'CLASSIFIED',note:' Dual siege limbs. Carry 1500kg / Lift 7500kg / Push 15000kg. No fine motor. +4 durability. Can target structures and vehicles. Classified.',dur_bonus:4,arms:2,str:24,fine_motor:false},
    ]},
  // ── HACKING ─────────────────────────────────────────────────────────────
  HACK_TERMINAL:{name:'Hacking Terminal',icon:'💻',loc:['int','ext'],
    tiers:[
      {name:'Basic Interface',slots:2,pwr:2,price:2500,dc:3,dur:3,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Basic: Enables DIRECT CONNECTION to adjacent devices, bypassing the EXTERNAL network layer remotely.'},
      {name:'ICE Breaker',slots:3,pwr:3,price:8000,dc:5,dur:4,rarity:'RARE',legality:'ILLEGAL',note:'ICE Breaker: DIRECT CONNECTION to adjacent devices, bypassing the EXTERNAL network layer. SMALL bonus to LOCK-ON and CYBER ATTACK. Illegal.'},
      {name:'Ghost Rig',slots:4,pwr:5,price:25000,dc:7,dur:4,rarity:'LIMITED',legality:'ILLEGAL',note:'Ghost Rig: DIRECT CONNECTION to adjacent devices, bypassing the EXTERNAL network layer. LARGE bonus to OBFUSCATE. Illegal.'},
    ]},
  DATA_CORE:{name:'Data Core',icon:'💾',loc:['core','int'],
    tiers:[
      {name:'Storage Unit',slots:1,pwr:1,price:1000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Storage Unit: Provides 1 MEMORY to the drone. When the operator is connected, adds to their DATACOM MEMORY capacity instead.'},
      {name:'Encrypted Core',slots:2,pwr:2,price:4000,dc:3,dur:4,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Encrypted Core: Provides 3 MEMORY to the drone. When the operator is connected, adds to their DATACOM MEMORY capacity instead. HACKPROOF.'},
      {name:'Quantum Vault',slots:3,pwr:3,price:15000,dc:5,dur:5,rarity:'RARE',legality:'CLASSIFIED',note:'Quantum Vault: Provides 5 MEMORY to the drone. When the operator is connected, adds to their DATACOM MEMORY capacity instead. HACKPROOF. Classified.'},
    ]},
  TECH_SCANNER:{name:'Tech Scanner',icon:'🔬',loc:['int','ext'],
    tiers:[
      {name:'Device Scanner',slots:1,pwr:1,price:1500,dc:2,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Enables Technology checks through the drone. SMALL penalty to Technology checks. Identifies device types and serial numbers.'},
      {name:'Diagnostic Rig',slots:2,pwr:2,price:5000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Enables Technology checks through the drone. No modifier to Technology checks. Full device analysis and diagnostics.'},
      {name:'Engineering Eye',slots:3,pwr:3,price:15000,dc:5,dur:4,rarity:'RARE',legality:'RESTRICTED',note:'Enables Engineering checks through the drone. SMALL bonus to Engineering checks. Blueprint reconstruction from scan data.'},
    ]},
  // ── COMMS ───────────────────────────────────────────────────────────────
  COMM_ARRAY:{name:'Comms Array',icon:'📻',loc:['core','int','ext'],
    tiers:[
      {name:'Short Range',slots:1,pwr:1,price:500,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Short-range comms array. 500m range, ECM resistance 0. Basic voice and data link.',comm_range:'500m',ecm:0},
      {name:'Long Range',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Long-range comms array. 50km range, ECM resistance 0. Standard drone communication.',comm_range:'50km',ecm:0},
      {name:'Encrypted Link',slots:2,pwr:3,price:6000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Encrypted comms link. 50km range, ECM resistance 1. Secure transmission resistant to interception.',comm_range:'50km',ecm:1},
      {name:'Quantum Comm',slots:3,pwr:5,price:25000,dc:5,dur:4,rarity:'RARE',legality:'RESTRICTED',note:'Quantum-entangled comms unit. Unlimited range, ECM resistance 2. Undetectable and unjammable. Restricted.',comm_range:'Unlimited',ecm:2},
    ]},
  COMM_JAMMER:{name:'Comms Jammer',icon:'📵',loc:['int','ext'],
    tiers:[
      {name:'Noise Generator',slots:2,pwr:2,price:2000,dc:3,dur:3,rarity:'UNCOMMON',legality:'ILLEGAL',note:'Noise-generating comms jammer, ECM 1. Disrupts comms in 30m radius. Illegal to operate.',ecm:1},
      {name:'Spectrum Jammer',slots:3,pwr:4,price:6000,dc:5,dur:3,rarity:'RARE',legality:'ILLEGAL',note:'Full-spectrum jammer, ECM 2. Disrupts all radio frequencies in 100m radius. Illegal.',ecm:2},
      {name:'Blackout System',slots:4,pwr:7,price:20000,dc:7,dur:4,rarity:'LIMITED',legality:'CLASSIFIED',note:'Total blackout system, ECM 3. Complete comms blackout in 500m radius. Classified.',ecm:3},
    ]},
  COMM_RELAY:{name:'Comms Relay',icon:'🔁',loc:['ext'],
    tiers:[
      {name:'Signal Booster',slots:1,pwr:1,price:800,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Signal booster relay. Doubles the range of all friendly comms within network.'},
      {name:'Relay Node',slots:2,pwr:2,price:3000,dc:2,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Multi-node relay hub. Serves as a communication relay point for the entire team.'},
      {name:'Network Core',slots:3,pwr:3,price:10000,dc:3,dur:4,rarity:'RARE',legality:'RESTRICTED',note:'Tactical network core. Manages a coordinated comms network for up to 20 units. Restricted.'},
    ]},
  BROADCAST_UNIT:{name:'Broadcast Unit',icon:'📢',loc:['ext'],
    tiers:[
      {name:'Speaker Array',slots:1,pwr:1,price:600,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'Loudspeaker and audio broadcast array. Voice modulation and high-volume announcement.'},
      {name:'Psych Array',slots:3,pwr:3,price:8000,dc:4,dur:3,rarity:'RARE',legality:'RESTRICTED',note:'Psychological broadcast array. Projects crowd-control frequencies causing disorientation. Restricted.'},
      {name:'Holo-Projector',slots:3,pwr:4,price:15000,dc:5,dur:4,rarity:'LIMITED',legality:'RESTRICTED',note:'Holographic projector unit. Creates holographic displays for deception and communication. Restricted.'},
    ]},
  // ── MEDICAL ─────────────────────────────────────────────────────────────
  MED_SYSTEM:{name:'Medical System',icon:'💊',loc:['core','int'],
    tiers:[
      {name:'First Aid Unit',slots:2,pwr:1,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Enables Medicine checks through the drone. SMALL penalty to Medicine checks. Field stabilisation of injured personnel.'},
      {name:'Medic Bay',slots:3,pwr:3,price:8000,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Enables Medicine checks through the drone. No modifier to Medicine checks. Capable of performing surgical procedures.'},
      {name:'Nano Medic',slots:4,pwr:5,price:25000,dc:6,dur:5,rarity:'RARE',legality:'RESTRICTED',note:'Enables Medicine checks through the drone. SMALL bonus to Medicine checks. Restricted.'},
    ]},
  TRAUMA_BAY:{name:'Trauma Bay',icon:'🏥',loc:['int'],
    tiers:[
      {name:'Stabiliser Pod',slots:2,pwr:2,price:4000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Stabilisation pod for critical patients. Keeps 1 critically injured patient stable during transport.'},
      {name:'Surgery Station',slots:4,pwr:4,price:15000,dc:5,dur:5,rarity:'RARE',legality:'LEGAL',note:'Full surgical station. Equipped for complex surgery on 1 patient.'},
      {name:'Cryo-Med',slots:5,pwr:6,price:40000,dc:6,dur:6,rarity:'LIMITED',legality:'RESTRICTED',note:'Cryogenic medical unit. Cryogenic preservation and controlled revival for fatally injured personnel. Restricted.'},
    ]},
  // ── ENGINEERING ─────────────────────────────────────────────────────────
  REPAIR_ARM:{name:'Repair Arm',icon:'🔧',loc:['ext'],
    tiers:[
      {name:'Tool Arm',slots:2,pwr:2,price:2000,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',note:' Enables Repair checks through the drone on external targets. SMALL penalty to Repair checks.'},
      {name:'Welder Arm',slots:3,pwr:3,price:5000,dc:3,dur:5,rarity:'UNCOMMON',legality:'LEGAL',note:' Enables Repair checks through the drone on external targets. No modifier to Repair checks. Handles structural and electronic repairs.'},
      {name:'Nano-Repair',slots:4,pwr:5,price:18000,dc:5,dur:5,rarity:'RARE',legality:'LEGAL',note:' Enables Repair checks through the drone on external targets. SMALL bonus to Repair checks. Expends NANITES for precision repairs.'},
    ]},
  FABRICATOR:{name:'Fabricator',icon:'⚙',loc:['int'],
    tiers:[
      {name:'Print Unit',slots:3,pwr:3,price:5000,dc:4,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:' Enables Craft checks through the drone. SMALL penalty to Craft checks. Prints small objects from raw materials.'},
      {name:'Micro-Factory',slots:5,pwr:5,price:20000,dc:6,dur:5,rarity:'RARE',legality:'RESTRICTED',note:' Enables Craft checks through the drone. No modifier to Craft checks. Prints complex components and drone parts. Restricted.'},
      {name:'Mol. Assembler',slots:6,pwr:8,price:60000,dc:8,dur:6,rarity:'LIMITED',legality:'CLASSIFIED',note:' Enables Craft checks through the drone. SMALL bonus to Craft checks. Constructs objects at the molecular level. Classified.'},
    ]},
  NANITE_SYS:{name:'Nanite Storage',icon:'🦠',loc:['core','int'],
    tiers:[
      {name:'Basic Tank',slots:1,pwr:1,price:1500,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Stores 1 NANITE for onboard systems. When operator is connected, adds to their NANITE pool instead.'},
      {name:'Standard Tank',slots:2,pwr:1,price:5000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Stores 3 NANITES for onboard systems. When operator is connected, adds to their NANITE pool instead.'},
      {name:'Advanced Tank',slots:3,pwr:2,price:15000,dc:4,dur:5,rarity:'RARE',legality:'LEGAL',note:'Stores 5 NANITES for onboard systems. When operator is connected, adds to their NANITE pool instead.'},
    ]},
  // ── UTILITY ─────────────────────────────────────────────────────────────
  STORAGE_BAY:{name:'Storage Bay',icon:'📦',loc:['int','ext'],
    tiers:[
      {name:'Small Hold',slots:2,pwr:0,price:800,dc:1,dur:4,rarity:'COMMON',legality:'LEGAL',note:'Small internal cargo hold. 5 SU capacity (5 small / 1 large item).'},
      {name:'Cargo Bay',slots:3,pwr:0,price:2000,dc:2,dur:5,rarity:'COMMON',legality:'LEGAL',note:'Standard cargo bay. 20 SU capacity (20 small / 6 large items).'},
      {name:'Secure Vault',slots:3,pwr:1,price:6000,dc:3,dur:7,rarity:'UNCOMMON',legality:'LEGAL',note:'Locked and encrypted secure vault. 10 SU capacity, tamper-proof and digitally secured.'},
      {name:'Cold Storage',slots:4,pwr:2,price:10000,dc:3,dur:5,rarity:'UNCOMMON',legality:'RESTRICTED',note:'Temperature-controlled cold storage. 18 SU bio-safe capacity for biological samples and perishables. Restricted.'},
    ]},
  SURVEY_KIT:{name:'Survey Kit',icon:'🗺',loc:['int','ext'],
    tiers:[
      {name:'Mapping Unit',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:' Enables Navigation checks through the drone. SMALL penalty to Navigation checks. Creates detailed terrain maps.'},
      {name:'Geo-Scanner',slots:3,pwr:3,price:6000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:' Enables Science checks through the drone. No modifier to Science checks. Mineral and structural analysis.'},
      {name:'Full Survey Rig',slots:4,pwr:4,price:15000,dc:5,dur:4,rarity:'RARE',legality:'LEGAL',note:' Enables Navigation and Science checks through the drone. SMALL bonus to Navigation and Science checks. Complete environmental survey capability.'},
    ]},
  RECORDER_SYS:{name:'Recorder System',icon:'🎥',loc:['int','ext'],
    tiers:[
      {name:'Cam Unit',slots:1,pwr:1,price:500,dc:1,dur:2,rarity:'COMMON',legality:'LEGAL',note:'360-degree camera and microphone array. Continuous video and audio recording.'},
      {name:'Witness Array',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Tamper-proof evidence recorder. Legally admissible, tamper-proof evidence recording.'},
      {name:'Covert Rec.',slots:2,pwr:2,price:8000,dc:4,dur:2,rarity:'RARE',legality:'ILLEGAL',note:'Covert surveillance recorder. Undetectable recording for intelligence operations. Illegal.'},
    ]},
  RESCUE_KIT:{name:'Rescue Kit',icon:'🆘',loc:['int','ext'],
    tiers:[
      {name:'Basic Rescue',slots:2,pwr:1,price:1500,dc:2,dur:4,rarity:'COMMON',legality:'LEGAL',note:' Enables Survival checks through the drone. SMALL penalty to Survival checks. Extraction tools and emergency beacon.'},
      {name:'SAR Package',slots:3,pwr:2,price:5000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:' Enables Survival checks through the drone. No modifier to Survival checks. Includes stretcher, fire suppression and signal flares.'},
      {name:'CSAR System',slots:4,pwr:3,price:15000,dc:4,dur:5,rarity:'RARE',legality:'RESTRICTED',note:' Enables Survival checks through the drone. SMALL bonus to Survival checks. Combat extraction and structural breaching tools. Restricted.'},
    ]},
  EXPLOSIVE_UNIT:{name:'Explosive Unit',icon:'💣',loc:['ext'],
    tiers:[
      {name:'Demo Charge',slots:1,pwr:0,price:1000,dc:2,dur:2,rarity:'UNCOMMON',legality:'ILLEGAL',note:'Single demolition charge. Single-use shaped explosive for structural breaching. Illegal.'},
      {name:'Mine Layer',slots:2,pwr:1,price:4000,dc:3,dur:3,rarity:'RARE',legality:'ILLEGAL',note:'Anti-personnel mine deployer. Deploys 3 proximity-triggered mines. Illegal.'},
      {name:'Grenade Rack',slots:2,pwr:1,price:5000,dc:3,dur:3,rarity:'RARE',legality:'ILLEGAL',note:'Grenade launcher rack. Stores and launches 5 grenades. Illegal.'},
      {name:'MIRV System',slots:9,pwr:2,price:25000,dc:7,dur:4,rarity:'LIMITED',legality:'CLASSIFIED',note:'MIRV warhead system. Multiple independently targeted warheads for area denial. Classified.'},
    ]},
  ENV_SYSTEM:{name:'Environment System',icon:'🌬',loc:['int'],
    tiers:[
      {name:'Temp Control',slots:2,pwr:2,price:2000,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Thermal regulation unit. Operates in extreme temperatures from -50 to +150°C.'},
      {name:'Radiation Shld',slots:2,pwr:2,price:4000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Radiation and vacuum shielding. Rated for radiation zones and hard vacuum.'},
      {name:'Extreme Env.',slots:3,pwr:3,price:12000,dc:4,dur:5,rarity:'RARE',legality:'LEGAL',note:'Extreme environment shell. Rated for corrosive atmospheres, high pressure and extreme temperatures.'},
    ]},
  // ── PROCESSING ──────────────────────────────────────────────────────────
  NEURAL_PROC:{name:'Neural Processor',icon:'🖥',loc:['core','int'],
    tiers:[
      {name:'Co-Processor',slots:1,pwr:1,price:1500,dc:2,dur:3,rarity:'COMMON',legality:'LEGAL',note:'Dedicated co-processing unit. +2 system bonus for all computational tasks.',sys_bonus:2},
      {name:'Neural Matrix',slots:2,pwr:2,price:6000,dc:3,dur:4,rarity:'UNCOMMON',legality:'LEGAL',note:'Neural-network accelerator. +4 system bonus, parallel processing architecture.',sys_bonus:4},
      {name:'Quantum Proc.',slots:3,pwr:4,price:20000,dc:5,dur:5,rarity:'RARE',legality:'RESTRICTED',note:'Quantum processing array. +7 system bonus, quantum-coherent computation. Restricted.',sys_bonus:7},
      {name:'Singularity Core',slots:7,pwr:7,price:70000,dc:8,dur:6,rarity:'UNIQUE',legality:'CLASSIFIED',note:'Singularity processing core. +12 system bonus, recursive self-optimizing matrix. Unique, classified.',sys_bonus:12},
    ]},
  // ── AI ──────────────────────────────────────────────────────────────────
  SKILL_MODULE:{name:'Skill Module',icon:'🧠',loc:['core','int'],
    tiers:[
      {name:'Basic AI',slots:2,pwr:3,price:25000,dc:3,dur:3,rarity:'UNCOMMON',legality:'LEGAL',note:'Basic AI skill module. Grants 1 skill at rank 3. Provides autonomous decision-making in assigned domain.',sys_bonus:1,skills_n:1,rank:3},
      {name:'Standard AI',slots:3,pwr:5,price:50000,dc:5,dur:4,rarity:'RARE',legality:'LEGAL',note:'Standard AI module. Grants 1 skill at rank 4 with +2 system bonus. Expanded operational autonomy.',sys_bonus:2,skills_n:1,rank:4},
      {name:'Advanced AI',slots:4,pwr:8,price:100000,dc:6,dur:5,rarity:'LIMITED',legality:'RESTRICTED',note:'Advanced AI package. Grants 1 skill at rank 6 with +3 system bonus. Near-expert autonomous operation. Restricted.',sys_bonus:3,skills_n:1,rank:6},
      {name:'Tactical AI',slots:5,pwr:12,price:200000,dc:8,dur:6,rarity:'UNIQUE',legality:'CLASSIFIED',note:'Tactical AI core. Grants 1 skill at rank 7 with +4 system bonus. Full combat-capable autonomous AI. Classified.',sys_bonus:4,skills_n:1,rank:7},
    ]},
};